app/ajax/urls.py
from django.urls import path
from django.shortcuts import redirect, reverse
from . import views

app_name = 'ajax'
urlpatterns = [
    path('validate_username', views.validate_username, name='validate_username'),
    path('dismiss_welcome_banner', views.dismiss_welcome_banner, name='dismiss_welcome_banner'),
    path('validate_topic_name', views.validate_topic_name, name='validate_topic_name'),
    path('posts/delete', views.delete_post, name='delete_post'),
]

app/boards/urls.py
from django.urls import path
from django.shortcuts import redirect, reverse
from . import views

app_name = 'boards'
urlpatterns = [
    path('', views.index, name='index'),
    path('boards', lambda request: redirect(reverse('boards:index'), permanent=True)),
    path('boards/<slug:board_slug>', views.board, name='board'),
    path('boards/<slug:board_slug>/<int:topic_id>', views.topic, name='topic'),
    path('boards/<slug:board_slug>/create/topic', views.create_topic, name='create_topic'),
]

app/django_boards/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from users import views as user_views


urlpatterns = [
    path('signup', user_views.signup_view, name='signup'),
    path('login', user_views.CustomLoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout', user_views.logout_view, name='logout'),

    path('', include('boards.urls')),
    path('ajax/', include('ajax.urls')),
    path('users/', include('users.urls')),

    path('tinymce/', include('tinymce.urls')),
    path('admin/', admin.site.urls),
    path('tz_detect/', include('tz_detect.urls')),
    path('_nested_admin/', include('nested_admin.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('profiles/<slug:profile_name>', views.profile_view, name='profile'),
]

app/boards/models.py
from django.db import models
from django.contrib.auth.models import User
from users.models import Profile
from django.shortcuts import reverse
from django.utils import timezone
from django.utils.text import slugify


class Board(models.Model):
    name = models.CharField(unique=True, max_length=40)
    description = models.CharField(max_length=100)
    last_updated = models.DateTimeField(auto_now=True)
    slug = models.CharField(unique=False, max_length=40)
    date_created = models.DateField(auto_now_add=True)

    def __str__(self):
        return f'Board: "{self.name}"'

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_url(self):
        return reverse('boards:board', args=(self.slug,))


class Topic(models.Model):
    name = models.CharField(max_length=100)
    last_updated = models.DateTimeField(auto_now=True)
    board = models.ForeignKey(Board, on_delete=models.CASCADE, related_name='topics')
    starter = models.ForeignKey(Profile, on_delete=models.SET_NULL, related_name='topics', null=True)
    created_on = models.DateTimeField(auto_now_add=True, editable=False)
    updated_by = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, related_name='+')
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'Topic | Board: {self.board.name} | User: {self.starter.name}'

    def __repr__(self):
        return f'Board: {self.board.name} | Starter: {self.starter.name}'

    def get_url(self):
        return reverse('boards:topic', args=(self.board.slug, self.id))

    @staticmethod
    def name_is_available_for_user(user, name):
        return Topic.objects.filter(name=name, starter=user.profile).count() == 0


class Post(models.Model):
    message = models.TextField(max_length=4000)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, related_name='posts')

    author = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, related_name='posts')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Topic: {self.topic.name} | Author: {self.author.name}'

    def __repr__(self):
        return f'Post | Topic: {self.topic.name} | Author: {self.author.name}'

    def get_url(self):
        return reverse('boards:topic', args=(self.topic.board.slug, self.topic.id))

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.topic.board.last_updated = timezone.now()
        self.topic.last_updated = timezone.now()
        self.topic.updated_by = self.author
        self.topic.board.save()
        self.topic.save()

app/boards/forms.py
from django import forms
from .models import Topic, Board, Post
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, Div, HTML
from tinymce.widgets import TinyMCE


class TopicCreationForm(forms.Form):
    name = forms.CharField()
    message = forms.CharField(
        widget=TinyMCE(attrs={'rows': 20})
    )

    def __init__(self, board, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.board = board
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Div(
                Field('name', css_class='js-validate-topic-name'),
                Div(css_class='text-danger form-errors text-right'),
                style='max-width: 400px;'
            ),
            Field('message')
        )


class PostForm(forms.Form):
    message = forms.CharField(
        widget=TinyMCE
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.form_show_labels = False

app/boards/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from .models import Board, Topic, Post
from .forms import TopicCreationForm, PostForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django import http


def index(request):
    boards = Board.objects.all()
    for board in boards:
        topics = board.topics.all()
        board.topic_count = topics.count()
        board.post_count = 0
        for topic in topics:
            board.post_count += topic.posts.count()

    # Show welcome banner for anonymous users who have not dismissed the banner
    show_welcome_banner = request.session.get('show_welcome_banner', True) and not request.user.is_authenticated

    context = {'boards': boards, 'show_welcome_banner': show_welcome_banner}
    return render(request, 'boards/index.html', context=context)


def board(request, board_slug):
    board_ = get_object_or_404(Board, slug=board_slug)
    context = {'board': board_}
    return render(request, 'boards/board.html', context=context)


def topic(request, board_slug, topic_id):
    board_ = get_object_or_404(Board, slug=board_slug)
    topic_ = get_object_or_404(Topic, pk=topic_id)
    form = PostForm()
    if request.POST:
        message = request.POST['message']
        if message is not None:
            user = request.user
            Post.objects.create(author=user.profile, message=message, topic=topic_)

    context = {'board': board_, 'topic': topic_, 'form': form}
    return render(request, 'boards/topic.html', context)


@login_required
def create_topic(request, board_slug):
    board_ = get_object_or_404(Board, slug=board_slug)
    form = TopicCreationForm(board_)
    if request.method == 'POST':
        name = request.POST.get('name')
        message = request.POST.get('message')
        if Topic.name_is_available_for_user(request.user, name):
            new_topic = Topic.objects.create(name=name, board=board_, starter=request.user.profile)
            new_post = Post.objects.create(author=request.user.profile, topic=new_topic, message=message)
            return redirect(new_post.get_url())
        else:
            messages.warning(request, 'This topic name is not available')
    context = {'board': board_, 'form': form}
    return render(request, 'boards/create_topic.html', context)

app/boards/templates/boards/board.html
{% extends 'base.html' %}

{% block content %}
	<nav aria-label="breadcrumb">
		<ol class="breadcrumb">
			<li class="breadcrumb-item"><a href="{% url 'boards:index' %}">Boards</a></li>
			<li class="breadcrumb-item active" aria-current="page">{{ board.name }}</li>
		</ol>
	</nav>
	<hr>
	<div class="text-center">
		<h2>{{ board.name }}</h2>
		<p>{{ board.description }}</p>
	</div>
	<hr>
	<table class="table">
		<thead class="thead-dark">
		<tr>
			<th scope="col">Name</th>
			<th scope="col">Posts</th>
			<th scope="col">Last updated</th>
			<th scope="col">Created on</th>
			<th scope="col">Starter</th>
		</tr>
		</thead>
		<tbody>
		{% if board.topics.all.count == 0 %}
			<tr>
				<td>Nothing to see here. Be the first to <a href="{% url 'boards:create_topic' board.slug %}">create a topic</a></td>
			</tr>
		{% else %}
			{% for topic in board.topics.all %}
				<tr>
					<th scope="row"><a href="{% url 'boards:topic' board.slug topic.id %}">{{ topic.name }}</a></th>
					<td>{{ topic.posts.count }}</td>
					<td>{{ topic.last_updated }}</td>
					<td>{{ topic.created_on }}</td>
					<td><a href="{% url 'users:profile' topic.starter.name %}">{{ topic.starter.name }}</a></td>
				</tr>
			{% endfor %}
		{% endif %}
		</tbody>
	</table>

	<a class="btn btn-outline-primary float-right" role="button" href="{% url 'boards:create_topic' board.slug %}">Create a
		new topic</a>
{% endblock %}

app/boards/templates/boards/create_topic.html
{% extends 'base.html' %}



{% block content %}
	<nav aria-label="breadcrumb">
		<ol class="breadcrumb">
			<li class="breadcrumb-item"><a href="{% url 'boards:index' %}">Boards</a></li>
			<li class="breadcrumb-item"><a href="{% url 'boards:board' board.slug %}">{{ board.name }}</a></li>
			<li class="breadcrumb-item active" aria-current="page">New topic</li>
		</ol>
	</nav>
	<div class="card">
		<div class="card-body">
			<h3>{{ board.name }} - New topic</h3>
			<hr>
			{% include 'forms/create_topic.html' %}
		</div>
	</div>

{% endblock %}

app/boards/templates/boards/index.html
{% extends 'base.html' %}

{% block content %}
	{% if not user.is_authenticated and not request.session.hide_welcome_banner %}
		<div class="collapse show" id="collapseJumbotron">
			<div class="jumbotron py-4">
				<button id="dismiss-welcome-banner" data-dismiss-welcome-banner-url="{% url 'ajax:dismiss_welcome_banner' %}"
				        type="button" class="close" aria-label="Close" data-toggle="collapse" data-target="#collapseJumbotron">
					<span style="font-size: 1.6em;" aria-hidden="true">&times;</span>
				</button>
				<h2 class="display-4">Welcome to Boards!</h2>
				<p class="lead">Here, you can speak your mind about anything you want! Well, just about anything.</p>
				<hr class="my-4">
				<p class="lead text-light">
					<a href="{% url 'signup' %}" class="btn btn-primary btn-lg" role="button" style="width: 7em;">Sign up</a>
					<a href="{% url 'login' %}" class="btn btn-primary btn-lg" role="button" style="width: 7em;">Log in</a>
				</p>
			</div>
		</div>
	{% endif %}
	<h2 class="text-primary">All boards</h2>
	<hr class="my-2">
	<table class="table">
		<thead class="thead-dark">
		<tr>
			<th scope="col">Name</th>
			<th scope="col">Description</th>
			<th scope="col">Topics/Posts</th>
			<th scope="col">Last updated</th>
		</tr>
		</thead>
		<tbody>
		{% for board in boards %}
			<tr>
				<th scope="row"><a href="{% url 'boards:board' board.slug %}">{{ board.name }}</a></th>
				<td>{{ board.description }}</td>
				<td>{{ board.topic_count }}/{{ board.post_count }}</td>

				<td>{{ board.last_updated }}</td>

			</tr>
		{% endfor %}
		</tbody>
	</table>

{% endblock %}

app/boards/templates/boards/topic.html
{% extends 'base.html' %}

{% block content %}

	<div class="modal" tabindex="-1" role="dialog" id="confirmDeleteModal">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-body">
					<p>Are you sure you want to delete this post?</p>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-outline-dark" data-dismiss="modal">Cancel</button>
					<button type="button" class="btn btn-danger" data-dismiss="modal" id="confirmDeleteButton">Delete</button>
				</div>
			</div>
		</div>
	</div>

	<nav aria-label="breadcrumb">
		<ol class="breadcrumb">
			<li class="breadcrumb-item"><a href="{% url 'boards:index' %}">Boards</a></li>
			<li class="breadcrumb-item"><a href="{% url 'boards:board' board.slug %}">{{ board.name }}</a></li>
			<li class="breadcrumb-item active" aria-current="page">{{ topic.name }}</li>
		</ol>
	</nav>

	{% for post in topic.posts.all %}
		<div class="card mb-4" id="post-{{ post.id }}">
			<div class="row no-gutters">
				<div class="col-2">
					<div class="card-profile-section" style="border-right: solid 1px #eee;">
						{% load static %}
						<div class="profile-picture-wrapper">
							<img src="{{ post.author.image.url }}" alt="profile image" class="img-fluid rounded">
						</div>
						<a href="{# TODO: Link to profile #}" class="text-decoration-none"><p class="text-center mt-2">
							<strong>{{ post.author.name }}</strong></p>
						</a>
					</div>
				</div>
				<div class="col">
					<div class="card-text-section">
						{{ post.message|safe }}
					</div>
				</div>
			</div>
			<div class="card-footer">
				<span class="text-muted" style="font-size: 0.8em">{{ post.created_at }}</span>
				<div class="post-actions">
					{% if request.user.is_superuser %}
						<a class="text-danger" delete-target-div="#post-{{ post.id }}"
						   delete-target-post="{{ post.id }}" data-delete-post-url="{% url 'ajax:delete_post' %}"
						   data-toggle="modal" data-target="#confirmDeleteModal"
						   href="javascript:void(0)">Delete</a>
					{% endif %}
				</div>
			</div>
		</div>
	{% endfor %}

	{% if request.user.is_authenticated %}
		<div class="collapse" id="collapseReply">
			<div class="card mb-4 border-dark">
				<form method="POST">

					<div class="row no-gutters">
						<div class="col-2" style="border-right: solid 1px #eee; margin: 0">
							<div class="card-profile-section">
								<div class="profile-picture-wrapper">
									<img src="{{ request.user.profile.image.url }}" alt="profile image" class="img-fluid rounded">
								</div>
								<a href="javascript:void(0);" class="text-decoration-none"><p class="text-center mt-2">
									<strong>{{ request.user.profile.name }}</strong></p>
								</a>
							</div>
						</div>
						<div class="col">
							<div class="card-text-section">
								{% load crispy_forms_tags %}
								<div class="text-right clearfix mb-2">
									<button id="closeAddReply" type="button" class="close" aria-label="Close" data-toggle="collapse"
									        data-target="#collapseReply"><span style="font-size: 1.6em;" aria-hidden="true">&times;</span>
									</button>
								</div>
								{% crispy form %}
							</div>
						</div>
					</div>
					<div class="card-footer">
						<div class="text-right">
							<button type="submit" class="btn btn-outline-success center-block" style="width: 8em">Submit</button>
						</div>
					</div>
				</form>
			</div>
		</div>
		<a class="btn btn-outline-primary float-right" role="button" data-toggle="collapse" data-target="#collapseReply"
		   href="javascript:void(0);" id="openAddReply">Add
			a reply</a>
	{% else %}
		<a class="btn btn-outline-primary float-right" role="button"
		   href="{% url 'login' %}?next={% url 'boards:topic' board.slug topic.id %}">Add a reply</a>
	{% endif %}
{% endblock %}