app/ajax/urls.py
from django.urls import path
from django.shortcuts import redirect, reverse
from . import views

app_name = 'ajax'
urlpatterns = [
    path('validate_username', views.validate_username, name='validate_username'),
    path('dismiss_welcome_banner', views.dismiss_welcome_banner, name='dismiss_welcome_banner'),
    path('validate_topic_name', views.validate_topic_name, name='validate_topic_name'),
    path('posts/delete', views.delete_post, name='delete_post'),
]

app/django_boards/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from users import views as user_views


urlpatterns = [
    path('signup', user_views.signup_view, name='signup'),
    path('login', user_views.CustomLoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout', user_views.logout_view, name='logout'),

    path('', include('boards.urls')),
    path('ajax/', include('ajax.urls')),
    path('users/', include('users.urls')),

    path('tinymce/', include('tinymce.urls')),
    path('admin/', admin.site.urls),
    path('tz_detect/', include('tz_detect.urls')),
    path('_nested_admin/', include('nested_admin.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/lib/templates/forms/create_topic.html
{% load crispy_forms_tags %}
<form method="POST" data-validate-topic-name-url="{% url 'ajax:validate_topic_name' %}">
	{% crispy form %}
	{% csrf_token %}
	<button type="submit" class="btn btn-outline-dark center-block" style="width: 8em">Create</button>
</form>

app/lib/templates/forms/login.html
{% load crispy_forms_tags %}
<form method="POST">
	{{ form|crispy }}
	{% csrf_token %}
	<div class="text-right">
		<button type="submit" class="btn btn-outline-dark center-block" style="width: 8em">Submit</button>
	</div>
</form>

app/lib/templates/forms/post.html
{% load crispy_forms_tags %}

<form method="POST">
	{% crispy form %}
		<div class="text-right">
		<button type="submit" class="btn btn-outline-success center-block" style="width: 8em">Submit</button>
	</div>
</form>

app/lib/templates/forms/signup.html
{% load crispy_forms_tags %}

<form method="POST" data-validate-username-url="{% url 'ajax:validate_username' %}">
	{% crispy form %}
	<div class="text-right">
		<button type="submit" class="btn btn-outline-dark center-block" style="width: 8em">Submit</button>
	</div>
</form>